[package]
name = "llm_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-core = "0.9.1"
tokio = { version = "1.34.0", features = ["full"] }
anyhow = "1.0.75"
solana-sdk = "2.2.1"
sqlx = "0.8.3"
tracing = "0.1.41"
redis = "0.29.1"
sea-orm = "1.1.7"
chrono = "0.4.40"
